### PR TITLE
Fixes literal periods in a pin not publishing/listening properly

### PR DESCRIPTION
**Pull request by ericnograles**
Initial attempt at addressing #66.  The periods in `resolveTopic` pin values will get "escaped" with dashes.

### CODE REVIEW

**Comment by nfantone** [comment]
All right, I checked this out and it turns out a pattern containing a `.` (dot) will end up generating an invalid routing key. AMQP treats RK as dot separated patterns, such as `foo.bar.#` where every word is evaluated separately.

So, @ericnograles, in your case, `version:v1.0` creates a `version.v1.0` routing key matching `version.*.0`, `version.*.*` or even `version.#` but _not_ `version.*` - which what you have configured in your listener.

And while your proposed solution _does_ work around this issue, it generates a new one: now a pattern containing a dot and a dash are effectively indistinguishable from each other. In other words, `version:v1.0` and `version:v1-0` would end up being answered by the same `.add` function.

This is a common concern in the AMQP world. In [this 2010 discussion on the official RabbitMQ mailing list](https://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2010-December/010205.html), there's an argument on whether it was actually a good idea to pick `.` as a separator character, which was brought up by a guy who wanted to match a site's URL like `http://jim.bob.mycoolproject`.

I don't see any elegant solution other that what you did here. But, I'd chose a different, rarer character (or sequence of characters) for escaping. Something like `>>` or `[:dot:]`.

**Comment by ericnograles** [comment]
Sounds good @nfantone, I'll make the change to the branch, and I agree with the rarer sequence of characters as a modification.  Let's use `[:dot:]` as that at least indicates to future devs that it's an escaped character and what the original was.

**Comment by nfantone** [comment]
@ericnograles I've just realized that we are only escaping one branch of the conditional. It should really apply to the string being pushed to the array.

Would you please..?

- [ ] Move "escaping" logic to a new function, so it looks:

```js
rk.push(escapePattern(options ? options[k] : topic[k]));
```

- [ ] Add a unit test to showcase the fix is working.

Thanks.

**Comment by ericnograles** [comment]
@nfantone ah, good call, didn't even think about that.  I'll push out a change in a bit.  Thanks!

**Comment by ericnograles** [comment]
Updated the branch @nfantone + unit tests also updated.  Looks like my PR is now failing Snyk for some odd reason though, anything I screwed up?

**Comment by nfantone** [comment]
No idea what's up with Snyk, but since you didn't introduce any new dependencies, there shouldn't be any problem.

This LGTM.

Thanks you very much for your cooperation, @ericnograles!

**Comment by ericnograles** [comment]
Anytime, @nfantone! Thanks for your guidance with this!

**Pull request merged**
